apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: a3nzu95hc-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/a3nzu95hc-java-quarkus-gitops